docker_image:                             # [linux64]
  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
cdt_name:                                 # [linux64]
  - cos7                                  # [linux64]
